# Generated by Django 4.2.1 on 2023-05-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_username', models.CharField(max_length=64)),
                ('us_pw', models.CharField(max_length=128)),
                ('us_api', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'tuser',
            },
        ),
        migrations.CreateModel(
            name='TInput',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('in_fname', models.CharField(max_length=40)),
                ('in_ftype', models.CharField(max_length=4)),
                ('in_contents', models.TextField()),
                ('in_date', models.DateField()),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tuser')),
            ],
            options={
                'db_table': 'tinput',
            },
        ),
        migrations.CreateModel(
            name='TContnets',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('co_indexs', models.TextField()),
                ('co_contents', models.TextField()),
                ('co_ketwords', models.TextField()),
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tinput')),
            ],
            options={
                'db_table': 'tcontnets',
            },
        ),
    ]
