# Generated by Django 4.2 on 2023-05-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textent',
            old_name='i_id',
            new_name='i',
        ),
        migrations.RenameField(
            model_name='tinput',
            old_name='p_id',
            new_name='us',
        ),
        migrations.RenameField(
            model_name='tsummary',
            old_name='i_id',
            new_name='i',
        ),
        migrations.RenameField(
            model_name='tword',
            old_name='i_id',
            new_name='i',
        ),
    ]
