# Generated by Django 4.2.1 on 2023-05-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_i_id_textent_i_rename_p_id_tinput_us_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TContnets',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('co_indexs', models.TextField()),
                ('co_contents', models.TextField()),
                ('co_ketwords', models.TextField()),
            ],
            options={
                'db_table': 'tcontnets',
            },
        ),
        migrations.RemoveField(
            model_name='tsummary',
            name='i',
        ),
        migrations.RemoveField(
            model_name='tword',
            name='i',
        ),
        migrations.RemoveField(
            model_name='tinput',
            name='in_words',
        ),
        migrations.AlterField(
            model_name='tinput',
            name='in_fname',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='TExtent',
        ),
        migrations.DeleteModel(
            name='TSummary',
        ),
        migrations.DeleteModel(
            name='TWord',
        ),
        migrations.AddField(
            model_name='tcontnets',
            name='i',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tinput'),
        ),
    ]
